FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn package

FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /app/target/load-balancing-project-1.0-SNAPSHOT.jar app.jar

EXPOSE 8081

CMD ["java", "-cp", "app.jar", "lb.WorkerServer", "8081"]